spring:

  datasource:
    url: jdbc:mysql://localhost:3306/withplay?useUnicode=true&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&MVCC=TRUE
    username: root
    password: madmin

  jpa:
    properties:
      hibernate:
#        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLW1pbG1pbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwzCg==