server:
  servlet:
    context-path: /api
cors:
  origin:
    url:

cloud:
  aws:
    credentials:
      accessKey: AKIAYTDTAZKBOTC7OA5X
      secretKey: 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
    s3:
      bucket: matchhere
    region:
      static: ap-northeast-2
    stack:
      auto: false

spring:
  datasource:
    url: jdbc:mysql://k5d106.p.ssafy.io:3306/withplay?useUnicode=true&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&MVCC=TRUE
    username: root
    password: qwer1234
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    properties:
      hibernate:
#        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt: # $ echo 'spring-boot-security-jwt-bjp-secret-key-sriends-project-for-ssafy-final-autonomous-project' | base64
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LWJqcC1zZWNyZXQta2V5LXNyaWVuZHMtcHJvamVjdC1mb3Itc3NhZnktZmluYWwtYXV0b25vbW91cy1wcm9qZWN0Cg==


mail:
  host: stmp.gmail.com
  port: 587
  username: ssafyD106@gmail.com
  password: FinalProjD106
  properties:
    mail:
      stmp:
        auth: true
        starttls:
          enable: true

logging:
  level:
    sriends: DEBUG

springdoc:
  version: '@springdoc.version@'
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operations-sorter: method
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  show-actuator: true
#  paths-to-match:
#    - /auth/**
#    - /users/**
#    - /teams/**
