server:
  servlet:
    context-path: /api
cors:
  origin:
    url:

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/withplay?useUnicode=true&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&MVCC=TRUE
    username: root
    password: ssafy

  jpa:
    properties:
      hibernate:
#        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt: # $ echo 'spring-boot-security-jwt-bjp-secret-key-sriends-project-for-ssafy-final-autonomous-project' | base64
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LWJqcC1zZWNyZXQta2V5LXNyaWVuZHMtcHJvamVjdC1mb3Itc3NhZnktZmluYWwtYXV0b25vbW91cy1wcm9qZWN0Cg==

logging:
  level:
    sriends: DEBUG

springdoc:
  version: '@project.version@'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  paths-to-match:
    - /api/**
    - /test/**
    - /**
